'use client';

import { FileText, Download, Loader } from 'lucide-react';

interface SummaryDisplayProps {
  title?: string;
  summary?: string;
  keyPoints?: string[];
  isLoading?: boolean;
  fileName?: string;
}

export function SummaryDisplay({
  title = 'Executive Summary',
  summary,
  keyPoints = [],
  isLoading = false,
  fileName = 'document',
}: SummaryDisplayProps) {

  const handleExport = () => {
    const docName = fileName.replace(/\.[^/.]+$/, '') || 'Document';
    const now = new Date().toLocaleString('en-IN', {
      dateStyle: 'medium',
      timeStyle: 'short',
    });

    const keyPointsHTML =
      keyPoints.length > 0
        ? `<section>
            <h2>Key Points</h2>
            <ol>
              ${keyPoints.map((p) => `<li>${p}</li>`).join('\n              ')}
            </ol>
          </section>`
        : '';

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${docName} — Summary</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      color: #1a1a2e;
      background: #fff;
      padding: 48px 56px;
      max-width: 800px;
      margin: auto;
    }
    .logo { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
    .logo-box {
      width: 40px; height: 40px; border-radius: 10px;
      background: linear-gradient(135deg, #4f46e5, #7c3aed);
      display: flex; align-items: center; justify-content: center;
    }
    .logo-box svg { width: 22px; height: 22px; stroke: #fff; fill: none; stroke-width: 2; }
    .logo-text h1 { font-size: 20px; font-weight: 700; color: #1e293b; }
    .logo-text p { font-size: 12px; color: #64748b; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }
    .meta { font-size: 12px; color: #64748b; margin-bottom: 32px; }
    .meta strong { color: #1e293b; }
    h2 {
      font-size: 16px; font-weight: 700; color: #1e293b;
      border-left: 4px solid #4f46e5;
      padding-left: 12px; margin-bottom: 14px;
    }
    section { margin-bottom: 32px; }
    p { font-size: 14px; line-height: 1.8; color: #334155; }
    ol { padding-left: 20px; }
    li { font-size: 14px; line-height: 1.9; color: #334155; margin-bottom: 4px; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    @media print {
      body { padding: 24px 32px; }
    }
  </style>
</head>
<body>
  <div class="logo">
    <div class="logo-box">
      <svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
    </div>
    <div class="logo-text">
      <h1>DocMind AI</h1>
      <p>Premium Document Analysis</p>
    </div>
  </div>
  <hr />
  <div class="meta">
    <strong>Document:</strong> ${docName} &nbsp;·&nbsp;
    <strong>Generated:</strong> ${now}
  </div>

  <section>
    <h2>Overview</h2>
    <p>${summary || 'No summary available.'}</p>
  </section>

  ${keyPointsHTML}

  <div class="footer">Generated by DocMind AI</div>

  <script>window.onload = () => window.print();</script>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, '_blank');
    if (!win) {
      const link = document.createElement('a');
      link.href = url;
      link.download = `${docName}-summary.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  };

  return (
    <div className="h-full flex flex-col bg-transparent p-6 relative overflow-hidden">
      <div className="flex-1 min-h-0 overflow-y-auto space-y-6 scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent pr-2">
        {/* Header */}
        <div className="flex items-start gap-4">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500/20 to-purple-500/20 border border-white/10 flex items-center justify-center flex-shrink-0">
            <FileText className="w-5 h-5 text-indigo-400" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">{title}</h2>
            <p className="text-xs text-indigo-300/70 mt-1 uppercase tracking-wider font-semibold">AI Extraction</p>
          </div>
        </div>

        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-16 h-[200px]">
            <div className="relative mb-4">
              <div className="w-12 h-12 border-2 border-indigo-500/20 rounded-full" />
              <div className="w-12 h-12 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin absolute inset-0" />
            </div>
            <p className="text-indigo-300 font-medium animate-pulse">Distilling insights…</p>
          </div>
        ) : summary ? (
          <div className="space-y-4">
            {/* Summary Card */}
            <div className="bg-white/[0.03] rounded-2xl p-5 border border-white/5 shadow-inner">
              <h3 className="text-sm font-semibold text-indigo-300 mb-3 uppercase tracking-wider">Overview</h3>
              <p className="text-gray-300 leading-relaxed text-sm">{summary}</p>
            </div>

            {/* Key Points */}
            {keyPoints.length > 0 && (
              <div className="bg-white/[0.03] rounded-2xl p-5 border border-white/5 shadow-inner">
                <h3 className="text-sm font-semibold text-indigo-300 mb-4 uppercase tracking-wider">Highlights</h3>
                <ul className="space-y-4">
                  {keyPoints.map((point, index) => (
                    <li key={index} className="flex gap-4 text-sm text-gray-300 group">
                      <span className="flex-shrink-0 w-6 h-6 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 rounded-full flex items-center justify-center text-xs font-bold group-hover:bg-indigo-500/30 transition-colors">
                        {index + 1}
                      </span>
                      <span className="leading-relaxed mt-0.5">{point}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-16 h-[200px] text-center">
            <div className="w-16 h-16 rounded-full bg-white/[0.02] border border-white/5 flex items-center justify-center mb-4">
               <FileText className="w-6 h-6 text-gray-600" />
            </div>
            <p className="text-gray-500 text-sm">Upload a document to generate an AI summary</p>
          </div>
        )}
      </div>

      {/* Export Button */}
      {summary && (
        <div className="mt-6 pt-5 border-t border-white/10 shrink-0">
          <button
            onClick={handleExport}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-white/5 hover:bg-white/10 text-white rounded-xl border border-white/10 transition-all font-medium text-sm hover:shadow-[0_0_20px_rgba(255,255,255,0.05)]"
          >
            <Download className="w-4 h-4 text-indigo-300" />
            Download Report
          </button>
        </div>
      )}
    </div>
  );
}
