'use client';

import { FileText, Download, Loader } from 'lucide-react';

interface SummaryDisplayProps {
  title?: string;
  summary?: string;
  keyPoints?: string[];
  isLoading?: boolean;
  fileName?: string;
}

export function SummaryDisplay({
  title = 'Executive Summary',
  summary,
  keyPoints = [],
  isLoading = false,
  fileName = 'document',
}: SummaryDisplayProps) {

  // ── Export as a proper PDF-like HTML printed page ───────────────────────────
  const handleExport = () => {
    const docName = fileName.replace(/\.[^/.]+$/, '') || 'Document';
    const now = new Date().toLocaleString('en-IN', {
      dateStyle: 'medium',
      timeStyle: 'short',
    });

    const keyPointsHTML =
      keyPoints.length > 0
        ? `<section>
            <h2>Key Points</h2>
            <ol>
              ${keyPoints.map((p) => `<li>${p}</li>`).join('\n              ')}
            </ol>
          </section>`
        : '';

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${docName} — Summary</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      color: #1a1a2e;
      background: #fff;
      padding: 48px 56px;
      max-width: 800px;
      margin: auto;
    }
    .logo { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
    .logo-box {
      width: 40px; height: 40px; border-radius: 10px;
      background: linear-gradient(135deg, #2563eb, #1e40af);
      display: flex; align-items: center; justify-content: center;
    }
    .logo-box svg { width: 22px; height: 22px; stroke: #fff; fill: none; stroke-width: 2; }
    .logo-text h1 { font-size: 20px; font-weight: 700; color: #1e293b; }
    .logo-text p { font-size: 12px; color: #64748b; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }
    .meta { font-size: 12px; color: #64748b; margin-bottom: 32px; }
    .meta strong { color: #1e293b; }
    h2 {
      font-size: 16px; font-weight: 700; color: #1e293b;
      border-left: 4px solid #2563eb;
      padding-left: 12px; margin-bottom: 14px;
    }
    section { margin-bottom: 32px; }
    p { font-size: 14px; line-height: 1.8; color: #334155; }
    ol { padding-left: 20px; }
    li { font-size: 14px; line-height: 1.9; color: #334155; margin-bottom: 4px; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    @media print {
      body { padding: 24px 32px; }
    }
  </style>
</head>
<body>
  <div class="logo">
    <div class="logo-box">
      <svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
    </div>
    <div class="logo-text">
      <h1>DocMind AI</h1>
      <p>Intelligent Document Analysis</p>
    </div>
  </div>
  <hr />
  <div class="meta">
    <strong>Document:</strong> ${docName} &nbsp;·&nbsp;
    <strong>Generated:</strong> ${now}
  </div>

  <section>
    <h2>Overview</h2>
    <p>${summary || 'No summary available.'}</p>
  </section>

  ${keyPointsHTML}

  <div class="footer">Generated by DocMind AI · Smart Extractive RAG</div>

  <script>window.onload = () => window.print();</script>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, '_blank');
    if (!win) {
      // Fallback: direct download as HTML file
      const link = document.createElement('a');
      link.href = url;
      link.download = `${docName}-summary.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  };

  return (
    <div className="h-full flex flex-col bg-gradient-to-br from-blue-50 to-indigo-50 p-6">
      <div className="flex-1 overflow-y-auto space-y-6">
        {/* Header */}
        <div className="flex items-start gap-3">
          <FileText className="w-8 h-8 text-blue-600 flex-shrink-0 mt-1" />
          <div>
            <h2 className="text-2xl font-bold text-gray-900">{title}</h2>
            <p className="text-sm text-gray-600">AI-Powered Analysis</p>
          </div>
        </div>

        {isLoading ? (
          <div className="flex items-center justify-center py-12">
            <div className="text-center">
              <Loader className="w-8 h-8 animate-spin text-blue-600 mx-auto mb-3" />
              <p className="text-gray-600">Analysing document…</p>
            </div>
          </div>
        ) : summary ? (
          <>
            {/* Summary Card */}
            <div className="bg-white rounded-lg shadow-sm p-5 border border-gray-100">
              <h3 className="text-base font-semibold text-gray-900 mb-3">Overview</h3>
              <p className="text-gray-700 leading-relaxed text-sm">{summary}</p>
            </div>

            {/* Key Points */}
            {keyPoints.length > 0 && (
              <div className="bg-white rounded-lg shadow-sm p-5 border border-gray-100">
                <h3 className="text-base font-semibold text-gray-900 mb-4">Key Points</h3>
                <ul className="space-y-3">
                  {keyPoints.map((point, index) => (
                    <li key={index} className="flex gap-3 text-sm text-gray-700">
                      <span className="flex-shrink-0 w-6 h-6 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center text-xs font-bold">
                        {index + 1}
                      </span>
                      <span className="leading-relaxed">{point}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Stats */}
            <div className="grid grid-cols-3 gap-3">
              <div className="bg-white rounded-lg shadow-sm p-3 border border-gray-100 text-center">
                <p className="text-xl font-bold text-blue-600">✓</p>
                <p className="text-xs text-gray-600 mt-1">Indexed</p>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-3 border border-gray-100 text-center">
                <p className="text-xl font-bold text-green-600">RAG</p>
                <p className="text-xs text-gray-600 mt-1">Powered</p>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-3 border border-gray-100 text-center">
                <p className="text-xl font-bold text-purple-600">AI</p>
                <p className="text-xs text-gray-600 mt-1">Smart</p>
              </div>
            </div>
          </>
        ) : (
          <div className="flex items-center justify-center py-12">
            <div className="text-center">
              <FileText className="w-12 h-12 text-gray-300 mx-auto mb-3" />
              <p className="text-gray-500">Upload a document to generate summary</p>
            </div>
          </div>
        )}
      </div>

      {/* Export Button */}
      {summary && (
        <div className="mt-6 pt-4 border-t border-gray-200">
          <button
            onClick={handleExport}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium text-sm shadow-sm"
          >
            <Download className="w-4 h-4" />
            Export Summary as PDF
          </button>
        </div>
      )}
    </div>
  );
}
